<a href="https://colab.research.google.com/github/DeepeshMadane/Machine-learning-/blob/main/cars.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [114]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [115]:
dataset = pd.read_csv('cars.csv')

In [116]:
dataset.head()

,Car_ID,Brand,Model,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Price
0,1,Toyota,Corolla,2018,50000,Petrol,Manual,First,15,1498,108,5,800000
1,2,Honda,Civic,2019,40000,Petrol,Automatic,Second,17,1597,140,5,1000000
2,3,Ford,Mustang,2017,20000,Petrol,Automatic,First,10,4951,395,4,2500000
3,4,Maruti,Swift,2020,30000,Diesel,Manual,Third,23,1248,74,5,600000
4,5,Hyundai,Sonata,2016,60000,Diesel,Automatic,Second,18,1999,194,5,850000

In [117]:
dataset=dataset.drop(columns=['Car_ID'],axis=1)

In [118]:
dataset.head()

,Brand,Model,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Price
0,Toyota,Corolla,2018,50000,Petrol,Manual,First,15,1498,108,5,800000
1,Honda,Civic,2019,40000,Petrol,Automatic,Second,17,1597,140,5,1000000
2,Ford,Mustang,2017,20000,Petrol,Automatic,First,10,4951,395,4,2500000
3,Maruti,Swift,2020,30000,Diesel,Manual,Third,23,1248,74,5,600000
4,Hyundai,Sonata,2016,60000,Diesel,Automatic,Second,18,1999,194,5,850000

In [119]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Brand              100 non-null    object
 1   Model              100 non-null    object
 2   Year               100 non-null    int64
 3   Kilometers_Driven  100 non-null    int64
 4   Fuel_Type          100 non-null    object
 5   Transmission       100 non-null    object
 6   Owner_Type         100 non-null    object
 7   Mileage            100 non-null    int64
 8   Engine             100 non-null    int64
 9   Power              100 non-null    int64
 10  Seats              100 non-null    int64
 11  Price              100 non-null    int64
dtypes: int64(7), object(5)
memory usage: 9.5+ KB

In [120]:
dataset.describe()

,Year,Kilometers_Driven,Mileage,Engine,Power,Seats,Price
count,100.00000,100.000000,100.000000,100.000000,100.000000,100.000000,1.000000e+02
mean,2018.39000,28150.000000,17.210000,1855.230000,158.130000,5.230000,1.574000e+06
std,1.17116,9121.375716,3.309902,631.311475,76.968137,0.750151,1.000265e+06
min,2016.00000,10000.000000,10.000000,999.000000,68.000000,4.000000,4.500000e+05
25%,2017.75000,22000.000000,15.000000,1462.000000,103.000000,5.000000,7.000000e+05
50%,2018.00000,27000.000000,17.000000,1774.000000,148.000000,5.000000,1.300000e+06
75%,2019.00000,32000.000000,19.000000,2143.000000,187.000000,5.000000,2.500000e+06
max,2021.00000,60000.000000,25.000000,4951.000000,396.000000,7.000000,4.000000e+06

In [121]:
missing_value=dataset.isnull().sum()

In [122]:
missing_value

Brand                0
Model                0
Year                 0
Kilometers_Driven    0
Fuel_Type            0
Transmission         0
Owner_Type           0
Mileage              0
Engine               0
Power                0
Seats                0
Price                0
dtype: int64

In [123]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [124]:
categorical_columns = [column for column in dataset.columns if dataset[column].dtype=="O"]

In [125]:
dataset[categorical_columns] = dataset[categorical_columns].apply(lambda x: le.fit_transform(x))

In [126]:
dataset.head()

,Brand,Model,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,Price
0,9,15,2018,50000,1,1,0,15,1498,108,5,800000
1,3,14,2019,40000,1,0,1,17,1597,140,5,1000000
2,2,30,2017,20000,1,0,0,10,4951,395,4,2500000
3,6,42,2020,30000,0,1,2,23,1248,74,5,600000
4,4,41,2016,60000,0,0,1,18,1999,194,5,850000

In [127]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Brand              100 non-null    int64
 1   Model              100 non-null    int64
 2   Year               100 non-null    int64
 3   Kilometers_Driven  100 non-null    int64
 4   Fuel_Type          100 non-null    int64
 5   Transmission       100 non-null    int64
 6   Owner_Type         100 non-null    int64
 7   Mileage            100 non-null    int64
 8   Engine             100 non-null    int64
 9   Power              100 non-null    int64
 10  Seats              100 non-null    int64
 11  Price              100 non-null    int64
dtypes: int64(12)
memory usage: 9.5 KB

In [128]:
X = dataset.iloc[:,:-1].values
y = dataset.iloc[:,-1].values

In [129]:
y = y.reshape(-1,1)

In [130]:
from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler(copy=True, with_mean=True, with_std=True)
sc_y = StandardScaler(copy=True, with_mean=True, with_std=True)
X = sc_x.fit_transform(X)
y = sc_y.fit_transform(y)

In [132]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42, shuffle =True)

polynomial

In [133]:
from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor(n_estimators=150,random_state=33)
model.fit(X_train,y_train)

<ipython-input-133-570b57351fbb>:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  model.fit(X_train,y_train)

RandomForestRegressor(n_estimators=150, random_state=33)

In [134]:
y_pred = model.predict(X_test)

In [135]:
from sklearn.metrics import r2_score
r2 = r2_score(y_test, y_pred)
r2

0.908761995727367